#!/usr/bin/env bash
# lib/launcher.sh -- install the runtime.
#
# Nothing here is generated from a template. The launcher and session manager
# are static files (lib/runtime/*.sh) copied verbatim and shared by every
# combination; all that varies is a small manifest written next to the model
# and a two-line shim per command. That is what keeps the combinations free of
# duplicated shell.
#
# Installed layout:
#   $ROOT/install.env    manifest read by the runtime
#   $ROOT/profiles.tsv   copied from the combination
#   $ROOT/help.txt       copied from the combination
#   $ROOT/client.sh      the DEFAULT client adapter (lib/clients/$CLIENT.sh)
#   $ROOT/client-<name>.sh  every client adapter, so any client can be selected
#                           at run time, not only the one baked into the combo
#   $BIN_DIR/local-ai-<backend>-server  launcher, shared by that backend
#   $BIN_DIR/local-ai-session           generic lifecycle manager (shared)
#   $BIN_DIR/$SERVER_CMD        shim -> local-ai-server
#   $BIN_DIR/$INSTALL_ID-<name> shim -> local-ai-session, pinned to that client

install_runtime() {
  info "Installing runtime..."

  install -m 644 "${COMBO_DIR}/profiles.tsv" "${INSTALL_ROOT}/profiles.tsv"
  install -m 644 "${COMBO_DIR}/help.txt"     "${INSTALL_ROOT}/help.txt"

  # Every client adapter is installed, not just the default: the client is an
  # orthogonal axis (see lib/run.sh), so a single model install can be driven by
  # any of them. client.sh stays as the default for the plain session command.
  install -m 644 "${LIB_DIR}/clients/${CLIENT}.sh" "${INSTALL_ROOT}/client.sh"
  local c
  for c in "${LIB_DIR}"/clients/*.sh; do
    install -m 644 "$c" "${INSTALL_ROOT}/client-$(basename "$c" .sh).sh"
  done

  # Bake only filenames, never absolute paths -- the runtime resolves
  # directories from $HOME. Keeps the install portable across machines and
  # users, and keeps the invoking user's name out of files people paste into
  # bug reports.
  local mmproj_name="" mtp_name=""
  if [[ -n "$MMPROJ"   ]]; then mmproj_name="$(basename "$MMPROJ")"; fi
  if [[ -n "$MTP_HEAD" ]]; then mtp_name="$(basename "$MTP_HEAD")"; fi

  cat > "${INSTALL_ROOT}/install.env" <<EOF
# Written by awesome-local-ai. Combination: ${COMBINATION}
# Read by local-ai-${BACKEND}-server and local-ai-session. No absolute paths.
INSTALL_ID="${INSTALL_ID}"
COMBINATION="${COMBINATION}"
DISPLAY_NAME="${DISPLAY_NAME}"
BACKEND="${BACKEND}"
ACCEL="${ACCEL}"
ROOT_ENV_VAR="${ROOT_ENV_VAR}"

MODEL_SUBDIR="${MODEL_SUBDIR}"
MODEL_FILE="$(basename "$MODEL_ARTIFACT")"
MMPROJ_FILE="${mmproj_name}"
MTP_FILE="${mtp_name}"
MODEL_ALIAS_DEFAULT="${MODEL_ALIAS_DEFAULT}"
MODEL_CACHE_ENV_VAR="${MODEL_CACHE_ENV_VAR:-}"

DEFAULT_PROFILE="${DEFAULT_PROFILE}"
SAFE_KV_TYPES="${SAFE_KV_TYPES}"
PROFILE_SCHEMA="${PROFILE_SCHEMA}"
REASONING_EFFORT_DEFAULT="${REASONING_EFFORT_DEFAULT}"
REASONING_EFFORTS="${REASONING_EFFORTS}"
SAMPLING_THINKING="${SAMPLING_THINKING}"
SAMPLING_INSTRUCT="${SAMPLING_INSTRUCT}"
SPEC_DRAFT_N_MAX="${SPEC_DRAFT_N_MAX}"
IMAGE_MIN_TOKENS="${IMAGE_MIN_TOKENS}"

DEFAULT_PORT="${DEFAULT_PORT}"

CLIENT="${CLIENT}"
DEFAULT_PROVIDER="${DEFAULT_PROVIDER}"
CONTEXT_LIMIT="${CONTEXT_LIMIT}"
OUTPUT_LIMIT="${OUTPUT_LIMIT}"

SERVER_CMD="${SERVER_CMD}"
SESSION_CMD="${SESSION_CMD}"
EOF
  ok "Manifest: ${INSTALL_ROOT}/install.env"

  local runtime_src="${LIB_DIR}/runtime/server-${BACKEND}.sh"
  [[ -f "$runtime_src" ]] || err \
    "Backend '${BACKEND}' has no runtime launcher (expected lib/runtime/server-${BACKEND}.sh).
       A backend that is not llama.cpp needs its own; see docs/adding-a-combination.md."

  install -m 755 "$runtime_src"                  "${BIN_DIR}/local-ai-${BACKEND}-server"
  install -m 755 "${LIB_DIR}/runtime/session.sh" "${BIN_DIR}/local-ai-session"

  _write_shim "$SERVER_CMD" "local-ai-${BACKEND}-server"

  # One session command per client, each pinned to that client. The default
  # client's command is $SESSION_CMD (${INSTALL_ID}-${CLIENT}); the others are
  # reachable as ${INSTALL_ID}-<client> (e.g. ./start.sh <id> --pi).
  local session_cmds=""
  for c in "${LIB_DIR}"/clients/*.sh; do
    local cn; cn="$(basename "$c" .sh)"
    [[ -n "$session_cmds" ]] && session_cmds="$session_cmds, "
    session_cmds="$session_cmds${INSTALL_ID}-${cn}"
    _write_shim "${INSTALL_ID}-${cn}" local-ai-session "$cn"
  done
  ok "Commands: ${SERVER_CMD}, ${session_cmds}"
}

# A shim is a couple of lines of intent: which install to use, (optionally)
# which client to run, and which generic runtime to hand them to.
_write_shim() {
  local name="$1" target="$2" client="${3:-}"
  local client_line=""
  [[ -n "$client" ]] && client_line="export LOCAL_AI_CLIENT=\"${client}\""
  cat > "${BIN_DIR}/${name}" <<EOF
#!/usr/bin/env bash
# ${name} -- ${COMBINATION}. Generated by awesome-local-ai; edit nothing here.
export LOCAL_AI_INSTALL_REL="${INSTALL_REL}"
${client_line}
exec "\$(dirname "\$(readlink -f "\${BASH_SOURCE[0]}")")/${target}" "\$@"
EOF
  chmod +x "${BIN_DIR}/${name}"
}
