// One definition per measure: its name, unit, and what it counts. Every page's headings and hovers read from here,
// so a number means the same thing wherever it appears. Add a measure here before showing it anywhere.

export interface Term {
  /** The heading or label. */
  name: string;
  /** What it counts, for the hover. */
  what: string;
}

export const GLOSSARY = {
  scoreOfRecord: { name: "Score", what: "The score of record: held-out tests passing when the finished run's final build is re-scored once more, under the current suite version. Only finished runs have one; it is the number to rank by." },
  scoreSummary: { name: "Score", what: "The score of record of this combination's finished runs: the median, the lowest and highest, and n, how many runs. With few runs, only large differences between combinations mean anything." },
  liveHeldOut: { name: "Live held-out", what: "Live: each story's held-out tests against the run's latest build, as the run goes. Provisional: it may come from an earlier suite version, and it never ranks anything." },
  storyHeldOut: { name: "Held-out", what: "This story's own held-out tests, passing against the build after it (the re-score of record where there is one, else live)." },
  agentTime: { name: "Agent time", what: "Wall time from the agent starting a story to it finishing, summed over stories: the model, its tools, and waits between sessions." },
  hoursPerStory: { name: "Hours per story", what: "Agent hours per story, over the finished runs: how long the combination takes to deliver a story. The median over runs, with the range." },
  outTokens: { name: "Output tokens", what: "Tokens the model wrote: its thinking, its replies and its tool calls (file contents, edits, commands)." },
  inputTokens: { name: "Input tokens", what: "Everything the model read to answer, summed over all its calls. Each call re-reads the whole conversation so far, mostly from its cache, so this grows with the number of calls." },
  calls: { name: "Tool calls", what: "Tool calls the agent made: reads, edits, writes and commands." },
  tokS: { name: "tok/s", what: "Output tokens over the time the story took (model, tools and all)." },
  decodeTokS: { name: "Decode tok/s", what: "Output tokens over the model's own generation time, where the harness timed the model." },
  compactions: { name: "Compactions", what: "Times the conversation was summarised to make room in the context." },
  nudges: { name: "Nudges", what: "Times the harness told the agent to carry on after it stopped without finishing." },
  timeSplit: { name: "Where the time went", what: "Every second of the story has one owner: compaction, a tool call, the model reading (prefill), the model writing (generation), the harness restarting the agent between sessions, or other." },
  thinking: { name: "Thinking", what: "Characters the model wrote as reasoning. It stays in the conversation, so a long block is re-read on every later call." },
  largestThinking: { name: "Largest thinking block", what: "The single longest piece of reasoning in the story, and when it came. One very long block tends to make every later call think more." },
  contextJump: { name: "Largest context jump", what: "The biggest growth in what the model reads between two consecutive calls: usually a long thinking block or a large file entering the conversation." },
  toolErrors: { name: "Tool errors", what: "Tool calls that returned an error, and commands that exited with a failure." },
  divergence: { name: "Differs from median", what: "This story run is more than 10% away from the combination's median for the same story: the same setup behaved differently." },

  // Run and story-run pages.
  runStatus: { name: "Status", what: "Where the run is: running, queued, finished, failed, stopped or cancelled, from its dbench job when it has one, else from its record." },
  machine: { name: "Machine", what: "The machine the run ran on: its dbench node, else the hardware its record names." },
  packVersion: { name: "Pack version", what: "The version of the spec pack the run built against. A run on an older version built a different spec." },
  suite: { name: "Suite", what: "The held-out test suite version the page scores against now. A score of record is from one suite version; one from another isn't comparable." },
  noScore: { name: "No score of record", what: "Only a finished run whose final build was re-scored has a score of record. Until then there is nothing to rank it by." },
  storyStrip: { name: "Stories", what: "One square per story in the run's scope, coloured by its own held-out tests against the run's latest build: all pass, some, none, not built yet, or being built now." },
  sqOk: { name: "all pass", what: "all its held-out tests pass" },
  sqPart: { name: "some pass", what: "some of its held-out tests pass" },
  sqBad: { name: "none pass", what: "none of its held-out tests pass" },
  sqUnbuilt: { name: "not built", what: "not built yet" },
  sqRunning: { name: "building", what: "being built now" },
  cost: { name: "Cost", what: "What the run's recorded stories cost: tokens, calls and speed. Stories not recorded yet aren't counted." },
  inputRead: { name: "Input tokens", what: "Everything the model read to answer, summed over all its calls: fresh input plus cache reads. Each call re-reads the whole conversation so far, so this grows with the number of calls." },
  cached: { name: "Cached", what: "The share of the input tokens served from the prompt cache rather than processed afresh." },
  prefillTokS: { name: "Prefill tok/s", what: "Fresh input tokens over the model's own reading time, where the harness timed the model." },
  draftAcceptance: { name: "Draft accepted", what: "The share of drafted tokens (speculative decoding: MTP or a draft model) that the model accepted. Only engines that draft report it." },
  heldOut: { name: "Held-out", what: "The held-out tests: flows the agent never sees, run against its build. Live progress after each story, and the score of record once the run is finished and re-scored." },
  cumulativeHeldOut: { name: "Whole suite so far", what: "Live: every story's held-out tests up to this one, against the build after this story." },
  heldOutAgreement: { name: "Live against record", what: "Whether the live figure after the last story matches the score of record. They count the same tests only when the live figure covers the whole suite." },
  jobs: { name: "Jobs", what: "Every dbench job of the run, oldest first. A job is one execution: a run restarted after a stop or a failure has more than one." },
  jobSubmitted: { name: "Submitted", what: "When the job was put on the machine's queue." },
  jobUpdated: { name: "Updated", what: "When dbench last reported on the job: when it ended, for one that has." },
  jobReason: { name: "Reason", what: "Why the job ended the way it did, as dbench recorded it." },
  compareRuns: { name: "Compare with another run", what: "This run's per-story numbers beside another run of the same combination. A difference of more than 10% from the other run is marked." },
  compareDiff: { name: "Differs by more than 10%", what: "This run's number is more than 10% above or below the other run's for the same story." },
  relatedRuns: { name: "Other runs of this combination", what: "Every other run of the same combination in this pack, whatever its status." },
  storyStatus: { name: "Story status", what: "DONE: the agent finished the story and its gates passed. PARTIAL: it stopped with the story unfinished (out of time, or the gates failed)." },
  modelCalls: { name: "Model calls", what: "Calls to the model in this story's conversation, counted from its event log. Each is one round of reading the conversation and writing a reply." },
  thinkingMedian: { name: "Thinking per call", what: "The median characters of reasoning per model call; and before and after the largest thinking block, to show whether one long block made later calls think more." },
  contextGrowth: { name: "Context", what: "Tokens the model read on the story's first call and on its last: how far the conversation grew." },
  toolsByName: { name: "Tools used", what: "Tool calls by tool, most used first." },
  longestTool: { name: "Longest tool call", what: "The single tool call that took longest, and what it ran." },
  signals: { name: "Signals", what: "Signs the harness saw in the conversation on its own, not relative to other runs: a command that hung. How much the model thought is judged against the combination's other runs instead." },
  conversation: { name: "Conversation profile", what: "What the agent's conversation on this story looked like, counted from its event log by a script: no LLM reads it." },
  againstCombination: { name: "Against the combination", what: "The same story in each of the combination's runs, on one scale. This story run is marked where it is more than 10% from the median of the other runs on time, output tokens, calls, thinking or its largest thinking block." },
  splitParts: { name: "Parts", what: "Each part's seconds and its share of the story's wall time. They add up to the wall time when the accounting check passes." },
  accountingCheck: { name: "Accounting check", what: "The split's own checks: parts sum to the wall time, none is negative, every tool call ended, and the wall time agrees with the agent's clock." },
  segPrefill: { name: "Prefill", what: "the model reading its input (including re-reading after a compaction or a resumed session)" },
  segDecode: { name: "Generation", what: "the model writing its output" },
  segModelUnsplit: { name: "Model, not split", what: "a model whose time wasn't split into reading and writing (a cloud model), together with the agent's own time" },
  segCompaction: { name: "Compaction", what: "the model summarising its own conversation to make room" },
  segTools: { name: "Tools", what: "the agent waiting on its own tool calls: its test runs, builds, file reads and edits, and any other command" },
  segBetweenSessions: { name: "Between sessions", what: "the harness starting the agent's next session after one ended: it waits before resuming an agent whose session ended in an error, and nudges one that stopped without committing" },
  segOther: { name: "Other", what: "the agent's own overhead between steps" },
  storyNav: { name: "Around this story", what: "The story before and after this one in the run, the same story in the combination's other runs, and the run and combination it belongs to." },

  // The ranking (overview) and the combination page.
  combination: { name: "Combination", what: "A stack: model, quant, engine and client, on one hardware class. Its short label; the full id (its folder under combinations/) on hover." },
  comboMachines: { name: "Machines", what: "The machines its runs ran on, counted or not." },
  pooledPassRate: { name: "Pooled", what: "Held-out tests passing over all held-out tests, summed over the same finished runs of record as the score: like with like, so it is fine beside the median. Running runs and other suite versions are never in it." },
  notCounted: { name: "Not counted", what: "Runs left out of this row's numbers, and why: running or queued (not finished), unscored (finished, but not re-scored under the current suite: never re-scored, or only under another version), failed, stopped or cancelled." },
  unranked: { name: "Not ranked", what: "No finished run with a score of record under the current suite, so there is nothing to rank it by. Live numbers never rank." },
  outPerStory: { name: "Output tokens per story", what: "Output tokens per story, over the finished runs of record: each run's own tokens per story, then the median over runs, with the range." },
  callsPerStory: { name: "Calls per story", what: "Tool calls per story, over the finished runs of record: how many steps the agent takes. Each run's own figure, then the median over runs, with the range. A cost measure, not a quality one." },
  inputPerStory: { name: "Input tokens per story", what: "Everything the model read per story, over the finished runs of record: each call re-reads the whole conversation, so this grows with the number of calls. The median over runs." },
  tokSOfRecord: { name: "tok/s", what: "Output tokens over the time the stories took (model, tools and all): each finished run of record's own rate, then the median over runs." },
  smallN: { name: "Too close to call", what: "With 5 runs or fewer per combination, a difference of 12 held-out tests or less can't separate two combinations: one combination's own runs spread that wide (methods review, 30 Sep)." },
  liveBadge: { name: "live", what: "Live progress over every run shown, running ones included, each on its latest build and possibly an older suite version. It never ranks anything: the ranking is on finished runs' scores of record." },
  liveHoursPerStory: { name: "h per story", what: "Live: agent hours per recorded story, over every run shown here, running ones included. Progress, not a ranking figure." },
  runsByStatus: { name: "Runs", what: "Every run of this combination in the pack, by status. Only finished runs with a score of record are in its numbers; the rest are counted apart." },
  matrix: { name: "Runs × stories", what: "One row per run, one column per story: each cell is one story run and links to it. Its colour is that story's held-out result; its text is the metric chosen above." },
  metricSwitch: { name: "Show", what: "What each cell's text shows. The colour always stays the story's held-out result." },
  storyMedian: { name: "Median", what: "Each story's median over this combination's finished runs (scored or not: a story's cost doesn't depend on the re-score). A cell more than 10% from it is flagged." },
  runTotalMetric: { name: "Run", what: "The run's own figure on the chosen metric: summed over its stories for minutes, tokens and calls; how many stories pass all their tests for held-out; its overall rate for tok/s." },
  storyRunHeldOut: { name: "Held-out", what: "This story's own held-out tests against the build right after it, recorded when the story finished. Only a run's final build is re-scored, so a story run has no score of record of its own." },
  runTimeSplit: { name: "Where the time went, per run", what: "One bar per run: every second of its recorded stories, summed, by owner. All runs on one scale, so a longer bar is a longer run." },
  mechanismTally: { name: "Why story runs differ", what: "Each story run flagged on the metric shown, by its mechanism: a label worked out from its conversation profile and usage against the same story's other runs, by fixed rules. No LLM reads anything." },
  mechHungCommand: { name: "hung command", what: "One tool call took 600 s or more (abnormal anywhere), or 40% or more of the story's time." },
  mechRestarted: { name: "restarted", what: "20% or more of the story went between agent sessions, and at least 2× the share in the story's other runs." },
  mechVerboseThinking: { name: "verbose thinking", what: "At least 2× the story's other runs on thinking per call, on thinking per call after its largest block, or on the largest block itself. Judged only against the same story in the same combination: what is a long block differs by model." },
  mechManySmallSteps: { name: "many small steps", what: "At least 1.5× the other runs' model calls, with thinking per call within 1.5× of theirs: more steps, not bigger ones." },
  mechCompactionHeavy: { name: "compaction-heavy", what: "20% or more of the story went on compaction, and at least 2× the share in the story's other runs." },
  mechSlowerGeneration: { name: "slower generation", what: "Decode tok/s at 75% or less of the story's other runs'." },
  mechUnexplained: { name: "unexplained", what: "None of the rules fired: thinking, steps, tool calls, compaction, restarts and generation speed are all near the other runs'. It differs for a reason the counts don't show." },
  mechNotRecorded: { name: "not recorded", what: "No conversation profile for this story run (recorded before the harness kept one), and nothing in its usage explains it." },
  mechPrecedence: { name: "Which label wins", what: "When several rules fire: hung command, then restarted (time sinks nothing else explains), then verbose thinking, many small steps, compaction-heavy, slower generation (causes before their consequences: more thinking and more steps grow the context, which brings compactions and slower generation). Every rule that fired is in the hover." },
  relatedCombinations: { name: "Other combinations of this model", what: "The same model with another quant, engine, client or hardware class, in this pack." },
  related: { name: "Related", what: "The machines this combination's runs ran on, and the other combinations of the same model." },
} as const satisfies Record<string, Term>;

export type TermId = keyof typeof GLOSSARY;
