// One definition per measure: its name, unit, and what it counts. Every page's headings and hovers read from here,
// so a number means the same thing wherever it appears. Add a measure here before showing it anywhere.

import { RECENT_END_S, SILENT_MINUTES } from "./overviewView.ts";

const SECONDS_PER_HOUR = 3600;

export interface Term {
  /** The heading or label. */
  name: string;
  /** What it counts, for the hover. */
  what: string;
}

export const GLOSSARY = {
  scoreOfRecord: { name: "Score", what: "The score of record: held-out tests passing when the finished run's final build is re-scored once more, under the current suite version. Only finished runs have one; it is the number to rank by." },
  scoreSummary: { name: "Score", what: "The score of record of this combination's finished runs: the median, the lowest and highest, and n, how many runs. With few runs, only large differences between combinations mean anything." },
  liveHeldOut: { name: "Live held-out", what: "Live: each story's held-out tests against the run's latest build, as the run goes. Provisional: it may come from an earlier suite version, and it never ranks anything." },
  storyHeldOut: { name: "Held-out", what: "This story's own held-out tests, passing against the build after it (the re-score of record where there is one, else live)." },
  agentTime: { name: "Agent time", what: "Wall time from the agent starting a story to it finishing, summed over stories: the model, its tools, and waits between sessions." },
  hoursPerStory: { name: "Hours per story", what: "Agent hours per story, over the finished runs: how long the combination takes to deliver a story. The median over runs, with the range." },
  outTokens: { name: "Output tokens", what: "Tokens the model wrote: its thinking, its replies and its tool calls (file contents, edits, commands)." },
  inputTokens: { name: "Input tokens", what: "Everything the model read to answer, summed over all its calls. Each call re-reads the whole conversation so far, mostly from its cache, so this grows with the number of calls." },
  calls: { name: "Tool calls", what: "Tool calls the agent made: reads, edits, writes and commands." },
  tokS: { name: "tok/s", what: "Output tokens over the time the story took (model, tools and all)." },
  decodeTokS: { name: "Decode tok/s", what: "Output tokens over the model's own generation time, where the harness timed the model." },
  compactions: { name: "Compactions", what: "Times the conversation was summarised to make room in the context." },
  nudges: { name: "Nudges", what: "Times the harness told the agent to carry on after it stopped without finishing." },
  timeSplit: { name: "Where the time went", what: "Every second of the story has one owner: compaction, a tool call, the model reading (prefill), the model writing (generation), the harness restarting the agent between sessions, or other." },
  thinking: { name: "Thinking", what: "Characters the model wrote as reasoning. It stays in the conversation, so a long block is re-read on every later call." },
  largestThinking: { name: "Largest thinking block", what: "The single longest piece of reasoning in the story, and when it came. One very long block tends to make every later call think more." },
  contextJump: { name: "Largest context jump", what: "The biggest growth in what the model reads between two consecutive calls: usually a long thinking block or a large file entering the conversation." },
  toolErrors: { name: "Tool errors", what: "Tool calls that returned an error, and commands that exited with a failure." },
  divergence: { name: "Differs from median", what: "This story run is more than 10% away from the combination's median for the same story: the same setup behaved differently." },

  // Run and story-run pages.
  runStatus: { name: "Status", what: "Where the run is: running, queued, finished, failed, stopped or cancelled, from its dbench job when it has one, else from its record." },
  machine: { name: "Machine", what: "The machine the run ran on: its dbench node, else the hardware its record names." },
  packVersion: { name: "Pack version", what: "The version of the spec pack the run built against. A run on an older version built a different spec." },
  suite: { name: "Suite", what: "The held-out test suite version the page scores against now. A score of record is from one suite version; one from another isn't comparable." },
  noScore: { name: "No score of record", what: "Only a finished run whose final build was re-scored has a score of record. Until then there is nothing to rank it by." },
  storyStrip: { name: "Stories", what: "One square per story in the run's scope, coloured by its own held-out tests against the run's latest build: all pass, some, none, not built yet, or being built now." },
  sqOk: { name: "all pass", what: "all its held-out tests pass" },
  sqPart: { name: "some pass", what: "some of its held-out tests pass" },
  sqBad: { name: "none pass", what: "none of its held-out tests pass" },
  sqUnbuilt: { name: "not built", what: "not built yet" },
  sqRunning: { name: "building", what: "being built now" },
  cost: { name: "Cost", what: "What the run's recorded stories cost: tokens, calls and speed. Stories not recorded yet aren't counted." },
  inputRead: { name: "Input tokens", what: "Everything the model read to answer, summed over all its calls: fresh input plus cache reads. Each call re-reads the whole conversation so far, so this grows with the number of calls." },
  cached: { name: "Cached", what: "The share of the input tokens served from the prompt cache rather than processed afresh." },
  prefillTokS: { name: "Prefill tok/s", what: "Fresh input tokens over the model's own reading time, where the harness timed the model." },
  draftAcceptance: { name: "Draft accepted", what: "The share of drafted tokens (speculative decoding: MTP or a draft model) that the model accepted. Only engines that draft report it." },
  heldOut: { name: "Held-out", what: "The held-out tests: flows the agent never sees, run against its build. Live progress after each story, and the score of record once the run is finished and re-scored." },
  cumulativeHeldOut: { name: "Whole suite so far", what: "Live: every story's held-out tests up to this one, against the build after this story." },
  heldOutAgreement: { name: "Live against record", what: "Whether the live figure after the last story matches the score of record. They count the same tests only when the live figure covers the whole suite." },
  jobs: { name: "Jobs", what: "Every dbench job of the run, oldest first. A job is one execution: a run restarted after a stop or a failure has more than one." },
  jobSubmitted: { name: "Submitted", what: "When the job was put on the machine's queue." },
  jobUpdated: { name: "Updated", what: "When dbench last reported on the job: when it ended, for one that has." },
  jobReason: { name: "Reason", what: "Why the job ended the way it did, as dbench recorded it." },
  compareRuns: { name: "Compare with another run", what: "This run's per-story numbers beside another run of the same combination. A difference of more than 10% from the other run is marked." },
  compareDiff: { name: "Differs by more than 10%", what: "This run's number is more than 10% above or below the other run's for the same story." },
  relatedRuns: { name: "Other runs of this combination", what: "Every other run of the same combination in this pack, whatever its status." },
  storyStatus: { name: "Story status", what: "DONE: the agent finished the story and its gates passed. PARTIAL: it stopped with the story unfinished (out of time, or the gates failed)." },
  modelCalls: { name: "Model calls", what: "Calls to the model in this story's conversation, counted from its event log. Each is one round of reading the conversation and writing a reply." },
  thinkingMedian: { name: "Thinking per call", what: "The median characters of reasoning per model call; and before and after the largest thinking block, to show whether one long block made later calls think more." },
  contextGrowth: { name: "Context", what: "Tokens the model read on the story's first call and on its last: how far the conversation grew." },
  toolsByName: { name: "Tools used", what: "Tool calls by tool, most used first." },
  longestTool: { name: "Longest tool call", what: "The single tool call that took longest, and what it ran." },
  signals: { name: "Signals", what: "Signs the harness saw in the conversation on its own, not relative to other runs: a command that hung. How much the model thought is judged against the combination's other runs instead." },
  conversation: { name: "Conversation profile", what: "What the agent's conversation on this story looked like, counted from its event log by a script: no LLM reads it." },
  againstCombination: { name: "Against the combination", what: "The same story in each of the combination's runs, on one scale, with each run's own held-out result for it. This story run is marked where it is more than 10% from the median of the other runs on held-out, time, output tokens, calls, thinking or its largest thinking block, with the mechanism: why it differs, by the combination page's rules, every rule that fired on hover." },
  whatDiffered: { name: "What differed", what: "This story run beside one other run of the same story in the combination, figure by figure: its held-out result, what it cost, where the time went and what the conversation looked like, with this run's figure over the other's. It starts with the most typical other run; choose any other. Counted from the records: no LLM." },
  acrossCombinations: { name: "Against every combination", what: "How every combination fares on this story: one row per combination that has recorded it, in the story page's order (the best median held-out result first, then the shortest agent time), each with its median and range over its valid finished runs: the story page's own medians. This story run's figures are on the first row, and its agent time is marked on every bar. Invalid runs and runs that haven't finished are in no median." },
  acrossRuns: { name: "Runs", what: "n: how many of the combination's valid finished runs recorded this story; its medians are over these (a measure that fewer of them recorded says its own n). Runs that recorded the story but haven't finished, and invalid runs, are counted beside it and are in no median." },
  typicalRun: { name: "most typical", what: "The other run of this story closest to the median row, picked by a fixed rule: among the other valid runs that recorded the story, the one with a figure for the most of the table's measures (held-out, agent time, output tokens, tool calls, thinking, largest thinking block); among those, the smallest sum of its distances from each median, each as a share of that median. A tie goes to the earlier run. An invalid run is never it." },
  ratioThisOverOther: { name: "This ÷ other", what: "This story run's figure over the other run's: 2× is twice as much, 0.5× half. Marked where the two are more than 10% apart." },
  thinkingAfterLargest: { name: "Thinking per call after the largest block", what: "The median characters of reasoning per model call after the story's largest thinking block: whether one long block made the later calls think more." },
  contextEnd: { name: "Context at the end", what: "Tokens the model read on the story's last call: how large the conversation had grown." },
  contextGrowthTimes: { name: "Context growth", what: "How many times the context grew from the story's first call to its last: what the model read on its last call over its first." },
  splitParts: { name: "Parts", what: "Each part's seconds and its share of the story's wall time. They add up to the wall time when the accounting check passes." },
  accountingCheck: { name: "Accounting check", what: "The harness checking its own arithmetic on this story's time split: the parts (prefill, generation, model not split, compaction, tools, between sessions, other) must add up to the wall time, none may be negative, the tools by kind must add up to Tools, every tool call must have ended, and the wall time must equal the agent's own clock plus the waits between sessions. If it fails, the story run's time figures can't be trusted; it never affects the held-out score. Unchecked: no time accounting was recorded to check." },
  segPrefill: { name: "Prefill", what: "the model reading its input (including re-reading after a compaction or a resumed session)" },
  segDecode: { name: "Generation", what: "the model writing its output" },
  segModelUnsplit: { name: "Model, not split", what: "a model whose time wasn't split into reading and writing (a cloud model), together with the agent's own time" },
  segCompaction: { name: "Compaction", what: "the model summarising its own conversation to make room" },
  segTools: { name: "Tools", what: "the agent waiting on its own tool calls: its test runs, builds, file reads and edits, and any other command" },
  segBetweenSessions: { name: "Between sessions", what: "the harness starting the agent's next session after one ended: it waits before resuming an agent whose session ended in an error, and nudges one that stopped without committing" },
  segOther: { name: "Other", what: "the agent's own overhead between steps" },
  invalidRun: { name: "Invalid", what: "The run's record marks it invalid: its result can't stand (it saw the reference build, say). It is shown, struck through with the reason on hover, and left out of every figure: rankings, medians, ranges, pooled scores, divergence medians and needs you." },
  intervened: { name: "intervened", what: "Someone did something to this run by hand (the operator, or the harness's watchdog): a frozen machine restarted, a silent tool call killed, a story ended at its cap. The run stays in every figure; this marks it so its numbers are read with that in mind. The hover lists each one." },
  interventions: { name: "Interventions", what: "Every line of the run's interventions.md, oldest first: what was done to the run by hand, by the operator or the harness's watchdog, and in which story. Repeated lines are shown once, with how many times." },
  storyNav: { name: "Around this story", what: "The story before and after this one in the run, the same story in the combination's other runs, and the run and combination it belongs to." },

  // The ranking (overview) and the combination page.
  combination: { name: "Combination", what: "A stack: model, quant, engine and client, on one hardware class. Its short label; the full id (its folder under combinations/) on hover." },
  comboMachines: { name: "Machines", what: "The machines its runs ran on, counted or not." },
  pooledPassRate: { name: "Pooled", what: "Held-out tests passing over all held-out tests, summed over the same finished runs of record as the score: like with like, so it is fine beside the median. Running runs and other suite versions are never in it." },
  notCounted: { name: "Not counted", what: "Runs left out of this row's numbers, and why: running or queued (not finished), unscored (finished, but not re-scored under the current suite: never re-scored, or only under another version), invalid (marked so in its record), failed, stopped or cancelled." },
  unranked: { name: "Not ranked", what: "No finished run with a score of record under the current suite, so there is nothing to rank it by. Live numbers never rank." },
  outPerStory: { name: "Output tokens per story", what: "Output tokens per story, over the finished runs of record: each run's own tokens per story, then the median over runs, with the range." },
  callsPerStory: { name: "Calls per story", what: "Tool calls per story, over the finished runs of record: how many steps the agent takes. Each run's own figure, then the median over runs, with the range. A cost measure, not a quality one." },
  inputPerStory: { name: "Input tokens per story", what: "Everything the model read per story, over the finished runs of record: each call re-reads the whole conversation, so this grows with the number of calls. The median over runs." },
  tokSOfRecord: { name: "tok/s", what: "Output tokens over the time the stories took (model, tools and all): each finished run of record's own rate, then the median over runs." },
  smallN: { name: "Too close to call", what: "With 5 runs or fewer per combination, a difference of 12 held-out tests or less can't separate two combinations: one combination's own runs spread that wide (methods review, 30 Sep)." },
  liveBadge: { name: "live", what: "Live progress over every run shown, running ones included, each on its latest build and possibly an older suite version. It never ranks anything: the ranking is on finished runs' scores of record." },
  liveHoursPerStory: { name: "h per story", what: "Live: agent hours per recorded story, over every run shown here, running ones included. Progress, not a ranking figure." },
  runsByStatus: { name: "Runs", what: "Every run of this combination in the pack, by status. Only finished runs with a score of record are in its numbers; the rest are counted apart." },
  matrix: { name: "Runs × stories", what: "One row per run, one column per story: each cell is one story run and links to it. Its colour is that story's held-out result; its text is the metric chosen above." },
  metricSwitch: { name: "Show", what: "What each cell's text shows. The colour always stays the story's held-out result." },
  storyMedian: { name: "Median", what: "Each story's median over this combination's finished runs (scored or not: a story's cost doesn't depend on the re-score; invalid runs left out). A cell more than 10% from it is flagged." },
  runTotalMetric: { name: "Run", what: "The run's own figure on the chosen metric: summed over its stories for minutes, tokens and calls; how many stories pass all their tests for held-out; its overall rate for tok/s." },
  storyRunHeldOut: { name: "Held-out", what: "This story's own held-out tests against the build right after it, recorded when the story finished. Only a run's final build is re-scored, so a story run has no score of record of its own." },
  runTimeSplit: { name: "Where the time went, per run", what: "One bar per run: every second of its recorded stories, summed, by owner. All runs on one scale, so a longer bar is a longer run." },
  mechanismTally: { name: "Why story runs differ", what: "Each story run flagged on the metric shown, by its mechanism: a label worked out from its conversation profile and usage against the same story's other runs, by fixed rules. No LLM reads anything." },
  mechHungCommand: { name: "hung command", what: "One tool call took 600 s or more (abnormal anywhere), or 40% or more of the story's time." },
  mechRestarted: { name: "restarted", what: "20% or more of the story went between agent sessions, and at least 2× the share in the story's other runs." },
  mechVerboseThinking: { name: "verbose thinking", what: "At least 2× the story's other runs on thinking per call, on thinking per call after its largest block, or on the largest block itself. Judged only against the same story in the same combination: what is a long block differs by model." },
  mechManySmallSteps: { name: "many small steps", what: "At least 1.5× the other runs' model calls, with thinking per call within 1.5× of theirs: more steps, not bigger ones." },
  mechCompactionHeavy: { name: "compaction-heavy", what: "20% or more of the story went on compaction, and at least 2× the share in the story's other runs." },
  mechSlowerGeneration: { name: "slower generation", what: "Decode tok/s at 75% or less of the story's other runs'." },
  mechUnexplained: { name: "unexplained", what: "None of the rules fired. They look only for what makes a story run cost more: a hung command, a restart, at least 2× the thinking or 1.5× the steps, heavy compaction, slower generation. It differs for a reason they don't look for (a story run that did less, say), or by less than they need." },
  mechNotRecorded: { name: "not recorded", what: "No conversation profile for this story run (recorded before the harness kept one), and nothing in its usage explains it." },
  mechPrecedence: { name: "Which label wins", what: "When several rules fire: hung command, then restarted (time sinks nothing else explains), then verbose thinking, many small steps, compaction-heavy, slower generation (causes before their consequences: more thinking and more steps grow the context, which brings compactions and slower generation). Every rule that fired is in the hover." },
  relatedCombinations: { name: "Other combinations of this model", what: "The same model with another quant, engine, client or hardware class, in this pack." },
  related: { name: "Related", what: "The machines this combination's runs ran on, and the other combinations of the same model." },

  // The overview and the machine pages.
  needsYou: { name: "Needs you", what: "Exceptions that ask for action, each linked to where it is resolved: a stuck story, an unreachable or idle machine, a run that failed or stopped in the last day, a finished run with no score of record, and stories whose time accounting failed its checks. Machines are looked at whatever the pack; runs in the pack and version chosen above. Invalid runs are left out." },
  needSilent: { name: "no activity", what: `The harness has reported nothing on this running story for ${SILENT_MINUTES} minutes or more. It rewrites the story's progress once a minute while the agent works, however slowly, so this silence means the harness, the agent or the machine has stopped. Stop it and restart the run, or read its log.` },
  needUnreachable: { name: "unreachable", what: "The machine's dbench service didn't answer. Nothing can be queued or stopped on it until it does." },
  needEnded: { name: "ended early", what: "The run failed or was stopped in the last day, before it finished: it has no score of record. Restart it from the machine's page, which resumes it at its first unfinished story." },
  needIdle: { name: "idle", what: "The machine answers, but nothing runs on it and nothing is queued: it is doing no benchmarking. Queue a run on its page." },
  needRescoreFault: { name: "re-score fault", what: "The finished run was re-scored under the current suite, but the re-score gave no score of record: the machine spoiled it (a harness fault, such as no browser), or it didn't reach the run's last story. Re-score it again." },
  needUnscored: { name: "not scored", what: "The run finished but has not been re-scored under the current suite, so it has no score of record and isn't ranked. Runs of an older spec version aren't listed: this suite can't score another spec." },
  needAccounting: { name: "accounting", what: "A story's time split failed its own checks (the parts don't sum to the wall time, one is negative, a tool call never ended, or the wall disagrees with the agent's clock), so where its time went can't be trusted (its held-out score is unaffected). The story run's page says what went wrong in plain words and what to do: usually, once the run has finished, recompute its record from the machine's full logs." },
  now: { name: "Now", what: "What each machine is doing: the run and story it is on, with the agent minutes on that story as the harness last reported them, or idle; and how many jobs wait in its queue." },
  storyMinutes: { name: "min on story", what: "Agent minutes on the running story, as the harness last reported them (it reports once a minute)." },
  queue: { name: "Queue", what: "Jobs waiting on the machine, in the order dbench will run them. The running job is not counted." },
  queuedOnly: { name: "waiting", what: "Nothing is running, but jobs are queued: dbench starts the next one when it can. If this lasts, check the machine." },
  hardware: { name: "Hardware", what: "What dbench reports about the machine: processor, cores, memory, graphics and operating system. Each exact machine spec is its own hardware class." },
  reachability: { name: "Reachability", what: "Whether the machine's dbench service answered the benchmarker's last request, and at which address." },
  historyRun: { name: "Run", what: "The run's id: a link to its page, with everything about it. The combination it belongs to heads the table." },
  nowRunning: { name: "Running", what: "The run the machine is on now and its story, with the agent minutes on that story as the harness last reported them; or idle, waiting (a queue but nothing running), or unreachable." },
  machinesList: { name: "Machines", what: "Every dbench node: the machines in the benchmarker's list and those dbench answered for. Each links to its page, with its hardware, installs, jobs and history." },
  os: { name: "OS", what: "The operating system dbench reports the machine runs." },
  jobPlace: { name: "Job", what: "Which of the run's dbench jobs this is: a run restarted after a stop or a failure has more than one. The dbench id is on hover." },
  runElapsed: { name: "run", what: "How long ago this attempt of the job started: the wall time of the run so far, not agent time." },
  dbenchVersion: { name: "dbench", what: "The version of the dbench service on the machine: the program that queues and runs the benchmark jobs there." },
  installs: { name: "Installs", what: "The combinations installed on the machine, which it can run. Each links to its combination's page once it has a run." },
  machineNow: { name: "Now", what: "The job running on this machine, with its live activity, then the queue in the order dbench will run it, then jobs that ended in the last day. Each job has its operations." },
  endedJobs: { name: "Ended in the last day", what: `Jobs that ended in the last ${RECENT_END_S / SECONDS_PER_HOUR} hours, by the end dbench recorded for each: finished, failed, stopped or cancelled. dbench keeps ended jobs for days; older ones are on their runs' pages. A failed, stopped or cancelled one can be restarted, which resumes its run at its first unfinished story.` },
  history: { name: "History", what: "Every run on this machine, by combination, then by pack and spec version: runs of different spec versions built different specs, so they are never grouped together. Each shows its status and its score of record." },
  activity: { name: "Activity", what: "Live: the running story's model calls and output tokens so far, the tasks written, and the agent's latest action. Claude runs count calls and tokens only at the end of a story." },
  machineRow: { name: "Machine", what: "A dbench node: the machine a run runs on. Its page has its hardware, installs, jobs and history." },

  // The story page.
  storyList: { name: "Stories", what: "Every story of this pack version that any run has in scope. Each opens its own page, keeping the comparison you chose." },
  storyHeldOutTests: { name: "Held-out tests", what: "How many held-out tests this story has, as the runs counted them. A run scored under another suite version can count a different number: each count is shown with how many runs counted it." },
  storyByCombination: { name: "By combination", what: "Every combination's attempt at this story: its median and range over its finished runs (agent time, output tokens, tool calls, held-out), then each of its runs. A run more than 10% from its combination's median is flagged, with the mechanism on hover." },
  storyCombinationMedian: { name: "Median", what: "This story's median over the combination's finished runs, with the lowest and highest and n, how many runs had the figure. Running runs aren't in it. It is the same median the combination page flags against." },
  storyLatestBuild: { name: "Latest build", what: "Live: this story's own held-out tests against the run's latest build, which may be several stories later. A later story can break an earlier one, so this can differ from the result right after the story." },
  setComparison: { name: "Set as comparison", what: "Show every other story run's numbers as a percentage of this one's. The choice is kept in the address, so a reload, a shared link and the back button keep it. Where its number is 0 or missing, each run shows its own." },
  storyTimeByCombination: { name: "Where the time went", what: "One bar per story run of this story, grouped by combination, all on one scale: a longer bar took longer. Every second has one owner: compaction, a tool call, the model reading or writing, the harness between sessions, or other." },
  storyNotBuilt: { name: "Not built", what: "Runs of this combination that haven't built this story: queued, still on an earlier story, or ended before it." },
  storyInEveryCombination: { name: "Every combination", what: "The story's own page: how every combination's runs did on this story, side by side." },
} as const satisfies Record<string, Term>;

export type TermId = keyof typeof GLOSSARY;
