// One definition per measure: its name, unit, and what it counts. Every page's headings and hovers read from here,
// so a number means the same thing wherever it appears. Add a measure here before showing it anywhere.
//
// Nothing here explains a fault, guesses a cause or tells the reader to do something: the page presents results,
// and what the server knows of faults goes to the monitor (GET /api/faults), never to a hover.

import { RECENT_END_S, SILENT_MINUTES } from "./overviewView.ts";

const SECONDS_PER_HOUR = 3600;

export interface Term {
  /** The heading or label. */
  name: string;
  /** What it counts, for the hover. */
  what: string;
}

export const GLOSSARY = {
  scoreOfRecord: { name: "Score", what: "How many of the held-out tests pass. Only finished runs have one; it is the number to rank by." },
  scoreSummary: { name: "Score", what: "The median, the lowest and highest of this combination's finished runs' scores, and n, how many runs. With few runs, only large differences between combinations mean anything." },
  liveHeldOut: { name: "Held-out", what: "How many of the held-out tests pass across the stories the run has finished." },
  storyHeldOut: { name: "Held-out", what: "This story's own held-out tests, passing after this story." },
  agentTime: { name: "Agent time", what: "Wall time from the agent starting a story to it finishing, summed over stories: the model, its tools, and waits between sessions." },
  hoursPerStory: { name: "Hours per story", what: "Agent hours per story, over the finished runs: how long the combination takes to deliver a story. The median over runs, with the range." },
  outTokens: { name: "Output tokens", what: "Tokens the model wrote: its thinking, its replies and its tool calls (file contents, edits, commands)." },
  inputTokens: { name: "Input tokens", what: "Everything the model read to answer, summed over all its calls. Each call re-reads the whole conversation so far, mostly from its cache, so this grows with the number of calls." },
  calls: { name: "Tool calls", what: "Tool calls the agent made: reads, edits, writes and commands." },
  tokS: { name: "Effective story tok/s", what: "Tokens per second averaged over the whole time it took to build a story, including tool calls, compactions, and critically, timeouts requiring interventions." },
  generatedTokS: { name: "Generated tok/s", what: "Tokens per second while the model is actually generating: output tokens over the time spent decoding. Reading the prompt, tool calls, compactions and waits are left out, so it is the speed the model is capable of, not the speed the story went at." },
  decodeTokS: { name: "Output tok/s", what: "Average tokens per second when actually generating tokens. Excludes tool calls, compactions etc." },
  engineSpeed: { name: "engine speed", what: "The model alone, where it was timed: output tokens per second while it generates, and fresh input tokens per second while it reads." },
  compactions: { name: "Compactions", what: "Times the conversation was summarised to make room in the context." },
  nudges: { name: "Nudges", what: "Times the agent was told to carry on after it stopped without finishing." },
  timeSplit: { name: "Where the time went", what: "Every second of the story has one owner: compaction, a tool call, the model reading (prefill), the model writing (generation), waiting between agent sessions, or other. Not available where the breakdown doesn't add up." },
  thinking: { name: "Thinking", what: "Characters the model wrote as reasoning. It stays in the conversation, so a long block is re-read on every later call." },
  largestThinking: { name: "Largest thinking block", what: "The single longest piece of reasoning in the story, and when it came. One very long block tends to make every later call think more." },
  contextJump: { name: "Largest context jump", what: "The biggest growth in what the model reads between two consecutive calls: usually a long thinking block or a large file entering the conversation." },
  toolErrors: { name: "Tool errors", what: "Tool calls that returned an error, and commands that exited with a failure." },
  divergence: { name: "Differs from median", what: "This story run is more than 10% away from the combination's median for the same story: the same setup behaved differently." },

  // Run and story-run pages.
  runStatus: { name: "Status", what: "Where the run is: running, queued, finished, failed, stopped or cancelled." },
  machine: { name: "Machine", what: "The machine the run ran on." },
  packVersion: { name: "Pack version", what: "The version of the spec pack the run built against. A run on an older version built a different spec." },
  suite: { name: "Suite", what: "The held-out test suite the page's scores come from. Scores from another suite aren't comparable." },
  noScore: { name: "No score yet", what: "Only a finished run has a score." },
  storyStrip: { name: "Stories", what: "One square per story in the run's scope, coloured by its own held-out tests: all pass, some, none, not built yet, or being built now." },
  sqOk: { name: "all pass", what: "all its held-out tests pass" },
  sqPart: { name: "some pass", what: "some of its held-out tests pass" },
  sqBad: { name: "none pass", what: "none of its held-out tests pass" },
  sqUnbuilt: { name: "not built", what: "not built yet" },
  sqRunning: { name: "building", what: "being built now" },
  runStories: { name: "Stories", what: "Each story the run covers, one row each: its own held-out result, where its time went, and what it cost. A story being built, or not yet reached, has an empty row. The run's totals are above the table." },
  cost: { name: "Cost", what: "What the run's stories cost: tokens, calls and speed." },
  inputRead: { name: "Input tokens", what: "Everything the model read to answer, summed over all its calls: fresh input plus cache reads. Each call re-reads the whole conversation so far, so this grows with the number of calls." },
  cached: { name: "Cached", what: "The share of the input tokens served from the prompt cache rather than processed afresh." },
  prefillTokS: { name: "Reading tok/s", what: "Average tokens per second when actually reading fresh input. Input served from the cache was not read again and is not counted." },
  draftAcceptance: { name: "Draft accepted", what: "The share of drafted tokens (speculative decoding: MTP or a draft model) that the model accepted. Only engines that draft report it." },
  heldOut: { name: "Held-out", what: "The held-out tests: flows the agent never sees, run against its build. One square per story in scope, coloured by how many of that story's own tests passed after it. The run's score heads the page once it is finished." },
  cumulativeHeldOut: { name: "Whole suite so far", what: "Every story's held-out tests up to this one, after this story." },
  ran: { name: "When it ran", what: "The machine the run ran on, when it was first queued there, and when it ended." },
  ranQueued: { name: "Queued", what: "When the run was first put on the machine's queue." },
  ranEnded: { name: "Ended", what: "When the run ended, for one that has." },
  compareRuns: { name: "Compare with other runs", what: "This run's per-story numbers beside those of any other runs you choose, from this combination or another, in the same pack and suite. A difference of more than 10% from this run is marked." },
  compareDiff: { name: "Differs by more than 10%", what: "The other run's number is more than 10% above or below this run's for the same story." },
  relatedRuns: { name: "Other runs of this combination", what: "Every other run of the same combination in this pack, whatever its status." },
  storyStatus: { name: "Story status", what: "DONE: the agent finished the story and its gates passed. PARTIAL: it stopped with the story unfinished (out of time, or the gates failed)." },
  modelCalls: { name: "Model calls", what: "Calls to the model in this story's conversation. Each is one round of reading the conversation and writing a reply." },
  thinkingMedian: { name: "Thinking per call", what: "The median characters of reasoning per model call; and before and after the largest thinking block, to show whether one long block made later calls think more." },
  contextGrowth: { name: "Context", what: "Tokens the model read on the story's first call and on its last: how far the conversation grew." },
  toolsByName: { name: "Tools used", what: "Tool calls by tool, most used first." },
  longestTool: { name: "Longest tool call", what: "The single tool call that took longest, and what it ran." },
  signals: { name: "Signals", what: "Signs in the conversation taken on their own, not relative to other runs: a command that hung. How much the model thought is judged against the combination's other runs instead." },
  conversation: { name: "Conversation profile", what: "What the agent's conversation on this story looked like." },
  conversationPage: { name: "Conversation", what: "The story run's conversation, happening by happening: every model call, tool call, message, compaction and wait, with the model server's requests and the machine's readings placed in it by time." },
  callTimeline: { name: "Timeline", what: "The story's span: each model call as a bar from its send to its end, as tall as its output; the tools it ran as a band under the line; each compaction as a line. Click a moment to go to that turn; drag across a span to show only its turns." },
  inOrder: { name: "The conversation", what: "Every turn in the order it happened: each model call with what it said and, under it, each tool it called with its argument, outcome and result; each message, compaction and wait; the engine's requests that no call matched, and the machine's readings. The overview above narrows it: by kind, by text, by a span of the timeline." },
  modelCall: { name: "Model calls", what: "Each call to the model: when it ended, how much it thought and wrote, which tools it called, the tokens it read and wrote, and why it stopped." },
  toolCall: { name: "Tool calls", what: "Each tool the agent ran: what it was given, how long it took, whether it failed, and the test counts its result printed." },
  compactionEvent: { name: "Compactions", what: "Each time the conversation was summarised to make room in the context: when, why, and how long it took." },
  betweenSessionsEvent: { name: "Waits between sessions", what: "Each wait between one agent session ending and the next starting." },
  harnessMessage: { name: "Messages", what: "What the agent was sent: the story's prompt, and the messages that told it to carry on." },
  engineRequest: { name: "Engine requests", what: "The model server's own account of each request it finished, placed in the conversation by time or by its tokens: what it read, what it generated, and how fast." },
  conditionReading: { name: "Machine readings", what: "Readings of the machine while the story ran: memory, swap, the GPU." },
  againstCombination: { name: "Against the combination", what: "The same story in each of the combination's runs, on one scale, with each run's own held-out result for it. This story run is marked where it is more than 10% from the median of the other runs on held-out, time, output tokens, calls, thinking or its largest thinking block, with the mechanism: why it differs, by the combination page's rules, every rule that fired on hover." },
  whatDiffered: { name: "What differed", what: "This story run beside one other run of the same story in the combination, figure by figure: its held-out result, what it cost, where the time went and what the conversation looked like, with this run's figure over the other's. It starts with the most typical other run; choose any other." },
  acrossCombinations: { name: "Against every combination", what: "Is this story run higher or lower quality on this story, and faster or slower, than each combination's finished runs? Its own combination first (this run against the combination's other runs), then every other combination with a finished run of the story, best quality first. Each answer is a verdict, then this run's figure and the combination's median; the range is on hover. Output tokens and tool calls are under detail." },
  acrossQuality: { name: "Quality on this story", what: "This story run's own held-out pass rate for this story against the combination's median. Same when they are at most one of this story's tests apart; better or worse beyond that." },
  acrossSpeed: { name: "Speed on this story", what: "This story run's agent time against the combination's median: same within 10% either way; beyond that, how many times faster or slower." },
  typicalRun: { name: "most typical", what: "The other run of this story closest to the median row, picked by a fixed rule: among the other runs that have the story, the one with a figure for the most of the table's measures (held-out, agent time, output tokens, tool calls, thinking, largest thinking block); among those, the smallest sum of its distances from each median, each as a share of that median. A tie goes to the earlier run." },
  ratioThisOverOther: { name: "This ÷ other", what: "This story run's figure over the other run's: 2× is twice as much, 0.5× half. Marked where the two are more than 10% apart." },
  thinkingAfterLargest: { name: "Thinking per call after the largest block", what: "The median characters of reasoning per model call after the story's largest thinking block: whether one long block made the later calls think more." },
  contextEnd: { name: "Context at the end", what: "Tokens the model read on the story's last call: how large the conversation had grown." },
  contextGrowthTimes: { name: "Context growth", what: "How many times the context grew from the story's first call to its last: what the model read on its last call over its first." },
  splitParts: { name: "Parts", what: "Each part's seconds and its share of the story's wall time." },
  segPrefill: { name: "Prefill", what: "the model reading its input (including re-reading after a compaction or a resumed session)" },
  segDecode: { name: "Generation", what: "the model writing its output" },
  segModelUnsplit: { name: "Model, not split", what: "a model whose time wasn't split into reading and writing because the record has no time for when reading ended (a cloud model, or a story whose server log gave none), together with the agent's own time" },
  segCompaction: { name: "Compaction", what: "the model summarising its own conversation to make room" },
  segTools: { name: "Tools", what: "the agent waiting on its own tool calls: its test runs, builds, file reads and edits, and any other command" },
  segBetweenSessions: { name: "Between sessions", what: "waiting to start the agent's next session after one ended: a pause before resuming an agent whose session ended in an error, and a message to one that stopped before the story was finished" },
  segOther: { name: "Other", what: "the agent's own overhead between steps" },
  thinkingActivity: { name: "Activity", what: "What the model's thinking was spent on, by activity class, for two combinations side by side. The classes are read from the thinking text itself, with no quality judgement in them. Only the stories both combinations ran are counted, so the task is the same on both sides, and each story contributes the median of that combination's runs." },
  collapsed: { name: "collapsed", what: "No held-out test passes in this story or in the stories next to it: three or more in a row. Its time and thinking are left out of the spread and per-story figures, so a run in that state does not read as a thrifty one." },
  intervened: { name: "intervened", what: "Something was done to this run by hand or by a watchdog: a frozen machine restarted, a silent tool call killed, a story ended at its cap. The run stays in every figure; this marks it so its numbers are read with that in mind. The hover lists each one." },
  utilisation: { name: "Utilisation", what: "What each machine ran over the last day, one lane each, with the gaps left empty. A machine runs one job at a time, so a run's stretch begins when the machine was free, not when the job was queued; the space left over is the machine standing idle. The figure on the right is the share of the day it was running something." },
  series: { name: "Series", what: "A run set: the runs of one combination named `<prefix>-rN`. One series is one experiment — a different engine build, quantisation or setting — so its runs are the only ones comparable with each other, and a combination's figures are over one series, never a median across several." },
  currentSeries: { name: "current", what: "The series the page's figures are over: the one with a run in hand, or the one worked on most recently." },
  interventions: { name: "Interventions", what: "What was done to the run by hand or by a watchdog, oldest first, and in which story. One silent tool call is one intervention, however many times the watchdog had to fire on it, and the count says how many times it did." },
  notCompared: { name: "Not compared with other runs", what: "This story run is left out of every story-by-story comparison: medians, spreads, marks and verdicts, here and on the pages that set story runs side by side. Its own figures stand, and so do its run's total and score." },
  storyNav: { name: "Around this story", what: "The story before and after this one in the run, the same story in the combination's other runs, and the run and combination it belongs to." },

  // The ranking (overview) and the combination page.
  combination: { name: "Combination", what: "A stack: model, quant, engine and client, on one hardware class. Its short label; the full id (its folder under combinations/) on hover." },
  comboMachines: { name: "Machines", what: "The machines its runs ran on, counted or not." },
  meanScore: { name: "Mean", what: "The mean of the same finished runs' scores: every held-out test they attempted, passed over attempted. The headline figure beside it is the median, so the two differ when one run is unlike the rest." },
  notCounted: { name: "Not counted", what: "Runs left out of this row's numbers: running or queued (not finished), pending (finished, no score yet), failed, stopped or cancelled." },
  unranked: { name: "Not ranked", what: "No finished run with a score, so there is nothing to rank it by." },
  outPerStory: { name: "Output tokens per story", what: "Output tokens per story: the median over finished runs, with the range." },
  callsPerStory: { name: "Calls per story", what: "Tool calls per story: how many steps the agent takes. The median over finished runs, with the range. A cost measure, not a quality one." },
  inputPerStory: { name: "Input tokens per story", what: "Everything the model read per story, over finished runs: each call re-reads the whole conversation, so this grows with the number of calls. The median over runs." },
  tokSOfRecord: { name: "Effective story tok/s", what: "Tokens per second averaged over the whole time it took to build a story, including tool calls, compactions, and critically, timeouts requiring interventions. The median over finished runs." },
  smallN: { name: "Too close to call", what: "With 5 runs or fewer per combination, a difference of 12 held-out tests or less can't separate two combinations: one combination's own runs spread that wide (methods review, 30 Sep)." },
  liveHoursPerStory: { name: "h per story", what: "Agent hours per story, over every run shown here, running ones included. Progress, not a ranking figure." },
  runsByStatus: { name: "Runs", what: "Every run of this combination in the pack, by status. Only finished runs with a score are in its numbers; the rest are counted apart." },
  matrix: { name: "Runs × stories", what: "One row per run, one column per story: each cell is one story run and links to it. Its colour is that story's held-out result; its text is the metric chosen above." },
  metricSwitch: { name: "Show", what: "What each cell's text shows. The colour always stays the story's held-out result." },
  storyMedian: { name: "Median", what: "Each story's median over this combination's finished runs. A cell more than 10% from it is flagged." },
  runTotalMetric: { name: "Run", what: "The run's own figure on the chosen metric: summed over its stories for minutes, tokens and calls; how many stories pass all their tests for held-out; its overall rate for tok/s." },
  storyRunHeldOut: { name: "Held-out", what: "This story's own held-out tests, passing after this story." },
  runTimeSplit: { name: "Where the time went, per run", what: "One bar per run: every second of its stories, summed, by owner. All runs on one scale, so a longer bar is a longer run." },
  mechanismTally: { name: "Why story runs differ", what: "Each story run flagged on the metric shown, by its mechanism: the likely reason it differs from the same story's other runs." },
  mechHungCommand: { name: "hung command", what: "One tool call took 600 s or more (abnormal anywhere), or 40% or more of the story's time." },
  mechRestarted: { name: "restarted", what: "20% or more of the story went between agent sessions, and at least 2× the share in the story's other runs." },
  mechVerboseThinking: { name: "verbose thinking", what: "At least 2× the story's other runs on thinking per call, on thinking per call after its largest block, or on the largest block itself. Judged only against the same story in the same combination: what is a long block differs by model." },
  mechManySmallSteps: { name: "many small steps", what: "At least 1.5× the other runs' model calls, with thinking per call within 1.5× of theirs: more steps, not bigger ones." },
  mechCompactionHeavy: { name: "compaction-heavy", what: "20% or more of the story went on compaction, and at least 2× the share in the story's other runs." },
  mechSlowerGeneration: { name: "slower generation", what: "Output tok/s at 75% or less of the story's other runs'." },
  mechUnexplained: { name: "unexplained", what: "None of the rules fired. They look only for what makes a story run cost more: a hung command, a restart, at least 2× the thinking or 1.5× the steps, heavy compaction, slower generation. It differs for a reason they don't look for (a story run that did less, say), or by less than they need." },
  mechNotRecorded: { name: "not recorded", what: "No conversation profile for this story run, and nothing in its usage explains it." },
  mechPrecedence: { name: "Which label wins", what: "When several rules fire: hung command, then restarted (time sinks nothing else explains), then verbose thinking, many small steps, compaction-heavy, slower generation (causes before their consequences: more thinking and more steps grow the context, which brings compactions and slower generation). Every rule that fired is in the hover." },
  predictability: { name: "Predictability", what: "How much the same story differs from one finished run of this combination to the next, in the model's thinking and in the story's time, beside how much it thinks and how long it takes. Over the stories that every one of its finished runs built." },
  thinkingSpread: { name: "Thinking spread", what: "How much the model's thinking for the same story differs from run to run: for each story, the variation across runs; then the median over stories. Lower means more predictable turnaround. Read it beside how much the model thinks." },
  thinkingPerStory: { name: "Thinking per story", what: "How much the model thinks in one story run: the median over the same finished runs' story runs. In characters where the log shows the thinking; in tokens for a cloud model, whose thinking text is withheld." },
  timeSpread: { name: "Time spread", what: "How much the agent time for the same story differs from run to run: for each story, the variation across runs; then the median over stories. Lower means more predictable turnaround. Read it beside the minutes per story." },
  minutesPerStory: { name: "Minutes per story", what: "Agent minutes of one story run: the median over the same finished runs' story runs." },
  spreadRuns: { name: "Finished runs", what: "How many finished runs the predictability figures are over. A spread is shown from three." },
  spreadTooFewRuns: { name: "—", what: "Needs three finished runs" },
  spreadNotRecorded: { name: "—", what: "No finished run recorded this." },
  relatedCombinations: { name: "Other combinations of this model", what: "The same model with another quant, engine, client or hardware class, in this pack." },
  related: { name: "Related", what: "The machines this combination's runs ran on, and the other combinations of the same model." },

  // The overview and the machine pages.
  machineSilent: { name: "no activity", what: `Nothing has been reported on this running story for ${SILENT_MINUTES} minutes or more. Progress is reported once a minute while the agent works, however slowly.` },
  machineUnreachable: { name: "unreachable", what: "The machine didn't answer the last request." },
  expertCache: { name: "Expert cache", what: "The hot experts this run's engine held in VRAM, and how much VRAM they took. An engine that keeps its experts in RAM copies the busiest ones to the card; where it sizes that cache to the VRAM that happens to be free, two runs of one combination can differ, and the one with less decodes more slowly." },
  runMemory: { name: "Memory", what: "What the model server held in memory as each story began: its total, and what its engine says of its prompt cache. Each engine says only what it says, so a figure an engine does not give is not shown." },
  memoryWeights: { name: "Model weights", what: "The size of the model's weights on disk: every file the server loads for it, including the speculative-decoding head where it has one." },
  memoryResident: { name: "Resident", what: "The model server's total memory in use as the story began, in GiB: the weights, the cache of earlier prompts and everything else it holds." },
  memoryPeak: { name: "Resident, peak", what: "The most the model server held as any story of this run began, in GiB." },
  memoryMedian: { name: "Resident, median", what: "The middle figure of the model server's memory as each story of this run began, in GiB." },
  promptCache: { name: "Prompt cache", what: "What the server keeps of earlier prompts so a turn can reuse them. gufo says how much its cache holds of what it may hold, and how many snapshots it skipped for lack of room. llama.cpp says how many entries it has evicted, and their size, since the server started: its figure grows across a run and starts again if the server restarts." },
  machineIdle: { name: "idle", what: "The machine answers, but nothing runs on it and nothing is queued." },
  referenceMachine: { name: "runs the reference only", what: "Every run on this machine is a reference run: a cloud model answering the same stories, as the yardstick the stacks are read against. It has a card of its own only while it is working." },
  now: { name: "Now", what: "What each machine is doing: the run and story it is on, with the agent minutes on that story as last reported, or idle; and how many jobs wait in its queue." },
  storyMinutes: { name: "min on story", what: "Agent minutes on the running story, as last reported (progress is reported once a minute)." },
  queue: { name: "Queue", what: "Jobs waiting on the machine, in the order they will run. The running job is not counted." },
  queuedOnly: { name: "waiting", what: "Nothing is running, but jobs are queued: the next one starts when it can." },
  hardware: { name: "Hardware", what: "What the machine reports about itself: processor, cores, memory, graphics and operating system. Each exact machine spec is its own hardware class." },
  reachability: { name: "Reachability", what: "Whether the machine answered the last request, and at which address." },
  historyRun: { name: "Run", what: "The run's id: a link to its page, with everything about it." },
  nowRunning: { name: "Running", what: "The run the machine is on now and its story, with the agent minutes on that story as last reported; or idle, waiting (a queue but nothing running), or unreachable." },
  machinesList: { name: "Machines", what: "Every machine in the list and every one that answered. Each links to its page, with its hardware, installs, jobs and history." },
  os: { name: "OS", what: "The operating system the machine reports it runs." },
  jobPlace: { name: "Job", what: "Which of the run's jobs this is: a run restarted after a stop or a failure has more than one." },
  runElapsed: { name: "run", what: "How long ago this attempt of the job started: the wall time of the run so far, not agent time." },
  dbenchVersion: { name: "dbench", what: "The version of dbench, the job service on the machine." },
  installs: { name: "Installs", what: "The combinations installed on the machine, which it can run. Each links to its combination's page once it has a run." },
  machineNow: { name: "Now", what: "The job running on this machine, with its activity, then the queue in the order it will run, then jobs that ended in the last day. Each job has its operations." },
  endedJobs: { name: "Ended in the last day", what: `Jobs that ended in the last ${RECENT_END_S / SECONDS_PER_HOUR} hours, by how each ended: finished, failed, stopped or cancelled. Older ones are on their runs' pages. A failed, stopped or cancelled one can be restarted, which resumes its run at its first unfinished story.` },
  history: { name: "History", what: "Every run on this machine, newest first: the one running, then those that ended, latest first, then the queue. Each row says its combination, the spec version it built against, its status, its stories and its score." },
  activity: { name: "Activity", what: "The running story's model calls and output tokens so far, the tasks written, and the agent's latest action." },
  machineRow: { name: "Machine", what: "A machine a run runs on. Its page has its hardware, installs, jobs and history." },

  // The story page.
  storyList: { name: "Stories", what: "Every story of this pack version that any run has in scope. Each opens its own page, keeping the comparison you chose." },
  storyHeldOutTests: { name: "Held-out tests", what: "How many held-out tests this story has. Where runs counted a different number, each count is shown with how many runs counted it." },
  storyByCombination: { name: "By combination", what: "Every combination's attempt at this story: its median and range over its finished runs (agent time, output tokens, tool calls, held-out), then each of its runs. A run more than 10% from its combination's median is flagged, with the mechanism on hover." },
  storyCombinationMedian: { name: "Median", what: "This story's median over the combination's finished runs, with the lowest and highest and n, how many runs had the figure. Running runs aren't in it. It is the same median the combination page flags against." },
  storyLatestBuild: { name: "Held-out now", what: "This story's own held-out tests as the run stands, which may differ from the result right after the story." },
  setComparison: { name: "Set as comparison", what: "Show every other story run's numbers as a percentage of this one's. The choice is kept in the address, so a reload, a shared link and the back button keep it. Where its number is 0 or missing, each run shows its own." },
  storyTimeByCombination: { name: "Where the time went", what: "One bar per story run of this story, grouped by combination, all on one scale: a longer bar took longer. Every second has one owner: compaction, a tool call, the model reading or writing, waiting between sessions, or other." },
  storyNotBuilt: { name: "Not built", what: "Runs of this combination that haven't built this story: queued, still on an earlier story, or ended before it." },
  storyInEveryCombination: { name: "Every combination", what: "The story's own page: how every combination's runs did on this story, side by side." },
} as const satisfies Record<string, Term>;

export type TermId = keyof typeof GLOSSARY;
